### ISSUE TITLE
Error N: 409

### ISSUE THREAD

**Issue by Victor-IT** [manuvarkey/kanboard-plugin-telegram#10]
What does it mean in our Kanboard context?
I'm trying to "Get chat id"
`Telegram error: Error N: 409, Description: Conflict: can't use getUpdates method while webhook is active`

**Comment by Victor-IT** [comment]
I think the reason is third-party services for managing the bot.

**Comment by manuvarkey** [comment]
getUpdates method cannot be used if you have setup any services that creates a webhook with your bot.
