### ISSUE TITLE
Error on the kanboard configuration page

### ISSUE THREAD

**Issue by gdl-joe** [manuvarkey/kanboard-plugin-telegram#12]
On settings >> integerations I get the following error messages instead of form fields:

Warning: include(plugins/Telegram/Template/config/integration.php): failed to open stream: No such file or directory in /www/htdocs/xxxxxx/kanboard/app/Core/Template.php on line 83

Warning: include(plugins/Telegram/Template/config/integration.php): failed to open stream: No such file or directory in /www/htdocs/xxxxxx/kanboard/app/Core/Template.php on line 83

Warning: include(): Failed opening 'plugins/Telegram/Template/config/integration.php' for inclusion (include_path='.:/usr/share/php:..') in /www/htdocs/xxxxxx/kanboard/app/Core/Template.php on line 83

**Comment by manuvarkey** [comment]
Can you mention the version of Kanboard, PHP and kanboard-plugin-telegram that you are using.

Also try reinstalling the plugin and make sure www-data user have read access to all sub directories of the plugin folder.

**Comment by gdl-joe** [comment]
html,body{background-color:#fff;color:#333;line-height:1.4;font-family:sans-serif,Arial,Verdana,Trebuchet MS;}
Hi,

 

thank you for the quick resonse.

 
 


Kanboard Version: 1.2.5

PHP-Version: PHP 7 as CGI

Plugin Telegram: latest (downloade a week ago from github)

 

Tried to change the permissions of all subfolders to 755, which did not help.

 

I will try to install again ....

 

best regards

 

Joachim

 

 



Manu Varkey schrieb am 23.08.2018 08:25:


Can you mention the version of Kanboard, PHP and kanboard-plugin-telegram that you are using.

Also try reinstalling the plugin and make sure www-data user have read access to all sub directories of the plugin folder.

**Comment by manuvarkey** [comment]
Also please see that the ownership of plugin folder, sub directories and contents should be www-data (or the user under which Apache server is run).
