### ISSUE TITLE
Individual notification not arriving, projects ok

### ISSUE THREAD

**Issue by tamielbr** [manuvarkey/kanboard-plugin-telegram#13]
Hi, i've managed to get the bot notifications working from projects just fine. But when I try to do the same for personal (user) nothign happens. Here are some settings:

I have integration to Telegram set and ``chat id`` retrieved and filled out (confirmed with manual and automatic modes). I have followed and asked for notifications of all projects and Telegram is checked. 

I tried creating tasks and @mentioning my name, but no notifications show. I would expect notifications to show on the private bot conversation. Is there anyway I could debug this? Thanks!

**Comment by manuvarkey** [comment]
1. Check if you have notifications enabled under My Profile-> Notifications when the user is logged in.
2. Notifications are not generated when a user mentions himself or does any action. You have to log in as a different user and does an action that affects the first user (like moving a task created by another user).

**Comment by tamielbr** [comment]
Excellent. Did the test and it worked. Many thanks.

**Comment by carlosnewmusic** [comment]
> 

It still doesn't send individual notifications through the bot, in telegram groups it works but not from the bot to telegram users, notifications arrive when a task is assigned or when something changes in the assigned task.
