### ISSUE TITLE
German translation crashes kanboard

### ISSUE THREAD

**Issue by sourcebert** [manuvarkey/kanboard-plugin-telegram#14]
**Actual behaviour**

On a fresh kanboard installation (only one admin user, no application settings other than language, no other plugins and without content) with german translation activated in application settings, kanboard crashes with HTTP Error 500 after installing telegram plugin. After removing telegram plugin directory manually kanboard works as expected. All other languages are working fine.

**Expected behaviour**

Kanboard works with german language setting.

**Steps to reproduce**

- install latest master branch of kanboard
- install telegram plugin
- set language to german in global application settings or user profile

_OR_

- install latest master branch of kanboard
- set language to german in global application settings or user profile
- install telegram plugin

**Configuration**

Application version: master (1.2.7)
PHP version: 7.2.13
PHP SAPI: cgi-fcgi
OS version: Linux 2.6.32-754.3.5.el6.x86_64
Database driver: sqlite
Database version: 3.20.1
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/73.0.3664.3 Chrome/73.0.3664.3 Safari/537.36

**Comment by ghost** [comment]
You could easily fix it: just add "," (comma) at the end of the line 8 in the file "...\Locale\de_DE\translations.php"

**Comment by manuvarkey** [comment]
Pushed the fix to upstream.

https://github.com/kanboard/website/pull/145
