### ISSUE TITLE
Is it working with SQLite?

### ISSUE THREAD

**Issue by ghost** [manuvarkey/kanboard-plugin-telegram#2]
Hi!
I tried to set up Telegram plugin for Kanboard. I completed all the steps to receive personal notifications:
copied files, created bot, its token and chat id. Then pasted token to settings and chat id to user profile. I checked box to receive personal notification through telegram in user settings. But I have not received any.

I took a look into sources and found info about mysql. Is MySQL needed to use plugin? Is it possible to use plugin with SQLite?

OS: Windows Server 2016
Web server: IIS 10.0
PHP: 7.2.1
DB: SQLite

**Comment by manuvarkey** [comment]
Notifications are independent of database. As a matter of fact I am using sqlite for Kanboard and the notifications are working for me. Can you follow the instructions under troubleshooting in the readme for this project ? That seems to be a common issue under windows.

**Comment by MichaelTunnell** [comment]
the notifications are working for me as well using a Linux Server.
