### ISSUE TITLE
2006 MySQL server has gone away

### ISSUE THREAD

**Issue by tamielbr** [manuvarkey/kanboard-plugin-telegram#21]
I suddenly started getting this error and narrowed it down to TelegramBot integration. Any activity that involves activating the bot circles for a long time and then throws the error below. I double checked all the API/chat id info, to no avail. Any ideas of what might be happening? PHP log has the same info.

Warning: Error while sending QUERY packet. PID=1691823 in /home/educacao/public_html/kanboard/vendor/fguillot/picodb/lib/PicoDb/StatementHandler.php on line 240
Internal Error: SQL error: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away
Fatal error: Uncaught PicoDb\SQLException: SQL error: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away in /home/educacao/public_html/kanboard/vendor/fguillot/picodb/lib/PicoDb/StatementHandler.php:351 Stack trace: #0 /home/educacao/public_html/kanboard/vendor/fguillot/picodb/lib/PicoDb/StatementHandler.php(245): PicoDb\StatementHandler->handleSqlError(Object(PDOException)) #1 /home/educacao/public_html/kanboard/vendor/fguillot/picodb/lib/PicoDb/Database.php(257): PicoDb\StatementHandler->execute() #2 /home/educacao/public_html/kanboard/vendor/fguillot/picodb/lib/PicoDb/Table.php(363): PicoDb\Database->execute('SELECT 1 FROM `...', Array) #3 /home/educacao/public_html/kanboard/app/Core/Session/SessionHandler.php(57): PicoDb\Table->exists() #4 [internal function]: Kanboard\Core\Session\SessionHandler->write('bc4a2efcbbc2b61...', 'csrf|a:0:{}hasR...') #5 [internal function]: session_write_close() #6 {main} thrown in /home/educacao/public_html/kanboard/vendor/fguillot/picodb/lib/PicoDb/StatementHandler.php on line 351'

**Comment by manuvarkey** [comment]
It may have something to do with wait timeouts. Can you try using a worker.

**Comment by tamielbr** [comment]
Hmmm, wouldn't know how to do it. No worries, feel free to close the issue.
