### ISSUE TITLE
Plugin send message with sync mode will cause latency while adding/modifing tasks

### ISSUE THREAD

**Issue by jemyzhang** [manuvarkey/kanboard-plugin-telegram#22]
while using this plugin, there's obvious latency for every action, is there anyway to use async mode to queue the message sending in background?

**Comment by manuvarkey** [comment]
You can enable a worker for Kanboard which will shift all notification related tasks to the background and fix your latency issue. Please see the following link.

https://docs.kanboard.org/en/latest/admin_guide/worker.html

**Comment by jemyzhang** [comment]
@manuvarkey Thansk for your reply, I will try this.
