### ISSUE TITLE
Unable to test overdue notifications

### ISSUE THREAD

**Issue by Snuupy** [manuvarkey/kanboard-plugin-telegram#26]
Edit: There is a notification on overdue tasks, just not via cli. How can this be triggered manually for testing purposes?

Hi,

I created a task with a due date and then tried:

`/var/www/app/cli notification:overdue-tasks`, and
`/var/www/app/cli cronjob`

Neither of them sent a telegram message about any overdue tasks. I also see this bug with other notification plugins as well, like Zulip (and I would assume Slack) since they are all forked from the same repo.

Are you able to reproduce?

**Comment by manuvarkey** [comment]
I am also unable to get notification. Is it working with any other notification plugin ? If not it may be better to raise this issue upstream.

**Comment by Snuupy** [comment]
According to https://github.com/kanboard/kanboard/issues/2270#issuecomment-230371680, "The task overdue event is not handled by the notification subscriber" so it doesn't look like it is possible to test it this way. Discussion to be continued here: https://github.com/kanboard/plugin-slack/issues/21
