### ISSUE TITLE
Locale

### ISSUE THREAD

**Issue by plyaskin** [manuvarkey/kanboard-plugin-telegram#28]
The notification language is used only from the main locale file (my locale is ru_RU). I added a new translation to the locale file, but the original translation is still in use :(

**Comment by manuvarkey** [comment]
If this is related to notification language, the same is handled by kanboard. For plugin related pages, the translation data is taken from this sub-directory of the plugin.

https://github.com/manuvarkey/kanboard-plugin-telegram/blob/master/Locale/ru_RU/translations.php

**Comment by plyaskin** [comment]
I tried, but it didn't work

**Comment by manuvarkey** [comment]
> The notification language is used only from the main locale file (my locale is ru_RU). I added a new translation to the locale file, but the original translation is still in use :(

Can you please elaborate on how and which files were edited ?

**Comment by plyaskin** [comment]
I edited locale file (ru_RU) for Telegram and for my plugin (not telegram), please try in your side. If I editing the locale file for KB so everything is ok, yes but I don't want to change anything in the source of KB, it is possible?

**Comment by manuvarkey** [comment]
Please share the contents of your locale file here.

**Comment by plyaskin** [comment]
https://github.com/kanboard/kanboard/issues/4688
