### ISSUE TITLE
Wrong timezone

### ISSUE THREAD

**Issue by plyaskin** [manuvarkey/kanboard-plugin-telegram#29]
For users with different time zones, it sends the same deadline to telegram.

**Comment by manuvarkey** [comment]
This issue seems to pertain to all Kanboard plugins. Can you varify with any other notification plugin ? If all are affected, please raise this issue upstream in the Kanboard project.

**Comment by plyaskin** [comment]
> This issue seems to pertain to all Kanboard plugins. Can you varify with any other notification plugin ? If all are affected, please raise this issue upstream in the Kanboard project.

This is not a plugin. KB is clean. Check for yourself.

**Comment by plyaskin** [comment]
> This issue seems to pertain to all Kanboard plugins. Can you varify with any other notification plugin ? If all are affected, please raise this issue upstream in the Kanboard project.

The issues are in KB and in the telegram. The telegram takes the time from DB, without any offsets to timezones.
About the issue of KB already made the bug ticket on KB GitHub.

**Comment by manuvarkey** [comment]
Please link to the upstream ticket.

**Comment by plyaskin** [comment]
https://github.com/kanboard/kanboard/issues/4688

**Comment by manuvarkey** [comment]
Issue tracked upstream.
