### ISSUE TITLE
Limiting the Amount of Notifications?

### ISSUE THREAD

**Issue by MichaelTunnell** [manuvarkey/kanboard-plugin-telegram#3]
Is there a way to limit what notifications are sent based on the type of change made in Kanboard? I really like this but sending a message for new tasks, new subtasks, new comments, editing tasks, etc can get pretty spamtastic pretty quickly. Is there a way to limit it for only new tasks or something like that?

**Comment by manuvarkey** [comment]
Actually this seems like it should be done in Kanboard upstream so that it will benefit all notification mechanisms. Can you open a feature request upstream ?

**Comment by manuvarkey** [comment]
Feature request opened upstream.

https://github.com/kanboard/kanboard/issues/3736

**Comment by MichaelTunnell** [comment]
I am so sorry. I spaced out on this task. I will comment on the one you made. Thanks
