### ISSUE TITLE
Telegram bot menu

### ISSUE THREAD

**Issue by plyaskin** [manuvarkey/kanboard-plugin-telegram#30]
Hi,

Do you know how to make a menu with /start and other commands that I can process with Kanboard?
Could you help me to implement such a case:
- I assign a task to the user
- The user receives a notification with the "Accept" and "Reject" buttons and must select
- If the user selects "Reject", he will be removed from the task.

**Comment by manuvarkey** [comment]
Please see this pull request. It has elements of what you are needing.

https://github.com/manuvarkey/kanboard-plugin-telegram/pull/9
