### ISSUE TITLE
Other users cannot see bot notifications.

### ISSUE THREAD

**Issue by duvvurisandeep** [manuvarkey/kanboard-plugin-telegram#31]
Hello Sir,
I have faced this problem.
kanboard-plugin-telegram successfully integrated to Kanboard. projectbot created and I get project & user notifications.
When I ask other users in telegram to check notification it shows blank to them.
Can you plese explain me in detail how this shoild ovecome.

**Comment by manuvarkey** [comment]
Hello,
Each user should enable telegram integration by completing the steps in "Integrations" to receive notifications. Also individual users should enable notifications from "Notifications" tab.

**Comment by duvvurisandeep** [comment]
Sir, only Administrators have right for Project Management and User Management in Kanboard. 
If users login kanboard 'Integrations' and 'Notifications' tab not available.

![image](https://user-images.githubusercontent.com/45380885/116665248-2a605e00-a9b7-11eb-946a-4a5400059ef5.png)

**Comment by manuvarkey** [comment]
Please see "My Profile" section.

**Comment by duvvurisandeep** [comment]
Sir, Sorry to disturb you.
 I have attached a doc. based on my Kanboard Telegram Integration with 3 sheets.
Kindly go through it where I have done mistake. If possible plese show via youtube video. the Telegram steps.
[Kanboard Telegram Integration.xlsx](https://github.com/manuvarkey/kanboard-plugin-telegram/files/6409115/Kanboard.Telegram.Integration.xlsx)

**Comment by manuvarkey** [comment]
Please see the folowing screencast.
[Usage screencast](https://user-images.githubusercontent.com/4415312/116866328-d78ddd00-ac28-11eb-889b-9b9aa554bed7.mp4)
