### ISSUE TITLE
Individual notifications from the bot to users do not work

### ISSUE THREAD

**Issue by carlosnewmusic** [manuvarkey/kanboard-plugin-telegram#33]
https://github.com/manuvarkey/kanboard-plugin-telegram/issues/13#issuecomment-981174441

PHP Version: 7.4
PHP SAPI: cgi-fcgi
HTTP Client: cURL
SO: Windows NT 10.0
Database driver mysql
Database version: 5.6

**Comment by manuvarkey** [comment]
Is it still an issue ? Are notifications being generated ? Please note that actions by a user1 will not create notifications for user1. Only actions by other users will create notifications for this user.

**Comment by carlosnewmusic** [comment]
you are right, I have already tested it and it works correctly.
