### ISSUE TITLE
Fatal error: Uncaught TypeError: Unsupported operand types: int + string in

### ISSUE THREAD

**Issue by sanychlxg** [manuvarkey/kanboard-plugin-telegram#34]
Fatal error: Uncaught TypeError: Unsupported operand types: int + string in /var/www/app/plugins/Telegram/Controller/TelegramController.php:52 Stack trace: #0 /var/www/app/app/Core/Controller/Runner.php(77): Kanboard\Plugin\Telegram\Controller\TelegramController->get_project_chat_id() #1 /var/www/app/app/Core/Controller/Runner.php(31): Kanboard\Core\Controller\Runner->executeController() #2 /var/www/app/index.php(9): Kanboard\Core\Controller\Runner->execute() #3 {main} thrown in /var/www/app/plugins/Telegram/Controller/TelegramController.php on line 52

it error if I add project intergration - Integration with third-party services
and Press[Get chat id]
my KANboard work in docker
conf docker:
version: '2'
services:
  kanboard:
    image: kanboard/kanboard:latest
    ports:
      - "18888:80"
      - "18443:443"
    restart: always
    volumes:
      - kanboard_data:/var/www/app/data
      - kanboard_plugins:/var/www/app/plugins
      - kanboard_ssl:/etc/nginx/ssl
volumes:
  kanboard_data:
  kanboard_plugins:
  kanboard_ssl:

but all files saved in >>> /var/snap/docker/common/var-lib-docker/volumes/docker_kanboard_data

**Comment by manuvarkey** [comment]
Please try the latest release. The bug has been fixed in this release. 

https://github.com/manuvarkey/kanboard-plugin-telegram/releases/download/v1.3.3/Telegram.zip

Sorry for the delay. Was busy with other works.

**Comment by sanychlxg** [comment]
Thank you)
