### ISSUE TITLE
Custom Notification

### ISSUE THREAD

**Issue by PFranck06** [manuvarkey/kanboard-plugin-telegram#35]
Hello i have 3 columns in my Kanboard: ToDo, Started, Done
Is it possible to send notification of ALL tasks who are not in the Done column yet each time you create a new tasks?
Anyway thanks for this plugin.

**Comment by manuvarkey** [comment]
I dont think it is possible. This is a feature that has to be done in Kanboard. If it gets implemented in Kanboard, you will receive the notifications in Telegram also.
