### ISSUE TITLE
The links to the tasks in telegram do not appear

### ISSUE THREAD

**Issue by carlosnewmusic** [manuvarkey/kanboard-plugin-telegram#36]
After a server migration domain, the links to the tasks in telegram do not appear.
what happens now:
![imagen](https://user-images.githubusercontent.com/19379457/173205733-876cda08-4b48-40b3-8fae-c8d627e72c93.png)
previously functioning correctly:
![imagen](https://user-images.githubusercontent.com/19379457/173205756-a7d866eb-66bb-45fd-a628-d851cacbca4e.png)

**Comment by manuvarkey** [comment]
Please check whether application URL is set.

![image](https://user-images.githubusercontent.com/4415312/173294781-07f0bec8-0252-4a4b-a3e4-b67cf3b30b69.png)
