### ISSUE TITLE
Suggestion: time range in which to send notifications directly to users

### ISSUE THREAD

**Issue by carlosnewmusic** [manuvarkey/kanboard-plugin-telegram#37]
Problem: some users receive notifications in the early hours due to different time zone. 

Solution: send notifications to the bot to users in a range of hours and sent in the silenced range send them when they enter the range of active hours base on their time zone

**Comment by manuvarkey** [comment]
This plugin only deals with the delivery of notifications. Generation of notification is handled by Kanboard notification system. This feature should be implemented upstream.
