### ISSUE TITLE
Deprecated: Creation of dynamic property Longman\TelegramBot\....

### ISSUE THREAD

**Issue by Kor-Phaeron** [manuvarkey/kanboard-plugin-telegram#41]
As adding a comment to task, or creating task, or at other different actions these error messages appears.

The link in browser tt this moment is: synology.me/?controller=CommentActionsController&action=save&plugin=KanboardCommentActions&task_id=48&project_id=13

<details>
  <summary>Error messages</summary>

  Deprecated: Creation of dynamic property Longman\TelegramBot\Entities\Message::$message_id is deprecated in /var/www/app/plugins/Telegram/vendor/longman/telegram-bot/src/Entities/Entity.php on line 83

Deprecated: Creation of dynamic property Longman\TelegramBot\Entities\Message::$from is deprecated in /var/www/app/plugins/Telegram/vendor/longman/telegram-bot/src/Entities/Entity.php on line 83

Deprecated: Creation of dynamic property Longman\TelegramBot\Entities\Message::$chat is deprecated in /var/www/app/plugins/Telegram/vendor/longman/telegram-bot/src/Entities/Entity.php on line 83

Deprecated: Creation of dynamic property Longman\TelegramBot\Entities\Message::$date is deprecated in /var/www/app/plugins/Telegram/vendor/longman/telegram-bot/src/Entities/Entity.php on line 83

Deprecated: Creation of dynamic property Longman\TelegramBot\Entities\Message::$text is deprecated in /var/www/app/plugins/Telegram/vendor/longman/telegram-bot/src/Entities/Entity.php on line 83

Deprecated: Creation of dynamic property Longman\TelegramBot\Entities\Message::$entities is deprecated in /var/www/app/plugins/Telegram/vendor/longman/telegram-bot/src/Entities/Entity.php on line 83

Deprecated: Creation of dynamic property Longman\TelegramBot\Entities\Message::$bot_username is deprecated in /var/www/app/plugins/Telegram/vendor/longman/telegram-bot/src/Entities/Entity.php on line 83

Deprecated: Creation of dynamic property Longman\TelegramBot\Entities\ServerResponse::$ok is deprecated in /var/www/app/plugins/Telegram/vendor/longman/telegram-bot/src/Entities/Entity.php on line 83

Deprecated: Creation of dynamic property Longman\TelegramBot\Entities\ServerResponse::$result is deprecated in /var/www/app/plugins/Telegram/vendor/longman/telegram-bot/src/Entities/Entity.php on line 83

Deprecated: Creation of dynamic property Longman\TelegramBot\Entities\ServerResponse::$raw_data is deprecated in /var/www/app/plugins/Telegram/vendor/longman/telegram-bot/src/Entities/Entity.php on line 83

Deprecated: Creation of dynamic property Longman\TelegramBot\Entities\ServerResponse::$bot_username is deprecated in /var/www/app/plugins/Telegram/vendor/longman/telegram-bot/src/Entities/Entity.php on line 83

Deprecated: Creation of dynamic property Longman\TelegramBot\Entities\Message::$message_id is deprecated in /var/www/app/plugins/Telegram/vendor/longman/telegram-bot/src/Entities/Entity.php on line 83

Deprecated: Creation of dynamic property Longman\TelegramBot\Entities\Message::$from is deprecated in /var/www/app/plugins/Telegram/vendor/longman/telegram-bot/src/Entities/Entity.php on line 83

Deprecated: Creation of dynamic property Longman\TelegramBot\Entities\Message::$chat is deprecated in /var/www/app/plugins/Telegram/vendor/longman/telegram-bot/src/Entities/Entity.php on line 83

Deprecated: Creation of dynamic property Longman\TelegramBot\Entities\Message::$date is deprecated in /var/www/app/plugins/Telegram/vendor/longman/telegram-bot/src/Entities/Entity.php on line 83

Deprecated: Creation of dynamic property Longman\TelegramBot\Entities\Message::$text is deprecated in /var/www/app/plugins/Telegram/vendor/longman/telegram-bot/src/Entities/Entity.php on line 83

Deprecated: Creation of dynamic property Longman\TelegramBot\Entities\Message::$entities is deprecated in /var/www/app/plugins/Telegram/vendor/longman/telegram-bot/src/Entities/Entity.php on line 83

Deprecated: Creation of dynamic property Longman\TelegramBot\Entities\Message::$bot_username is deprecated in /var/www/app/plugins/Telegram/vendor/longman/telegram-bot/src/Entities/Entity.php on line 83

Deprecated: Creation of dynamic property Longman\TelegramBot\Entities\ServerResponse::$ok is deprecated in /var/www/app/plugins/Telegram/vendor/longman/telegram-bot/src/Entities/Entity.php on line 83

Deprecated: Creation of dynamic property Longman\TelegramBot\Entities\ServerResponse::$result is deprecated in /var/www/app/plugins/Telegram/vendor/longman/telegram-bot/src/Entities/Entity.php on line 83

Deprecated: Creation of dynamic property Longman\TelegramBot\Entities\ServerResponse::$raw_data is deprecated in /var/www/app/plugins/Telegram/vendor/longman/telegram-bot/src/Entities/Entity.php on line 83

Deprecated: Creation of dynamic property Longman\TelegramBot\Entities\ServerResponse::$bot_username is deprecated in /var/www/app/plugins/Telegram/vendor/longman/telegram-bot/src/Entities/Entity.php on line 83

Deprecated: Creation of dynamic property Longman\TelegramBot\Entities\Message::$message_id is deprecated in /var/www/app/plugins/Telegram/vendor/longman/telegram-bot/src/Entities/Entity.php on line 83

Deprecated: Creation of dynamic property Longman\TelegramBot\Entities\Message::$from is deprecated in /var/www/app/plugins/Telegram/vendor/longman/telegram-bot/src/Entities/Entity.php on line 83

Deprecated: Creation of dynamic property Longman\TelegramBot\Entities\Message::$chat is deprecated in /var/www/app/plugins/Telegram/vendor/longman/telegram-bot/src/Entities/Entity.php on line 83

Deprecated: Creation of dynamic property Longman\TelegramBot\Entities\Message::$date is deprecated in /var/www/app/plugins/Telegram/vendor/longman/telegram-bot/src/Entities/Entity.php on line 83

Deprecated: Creation of dynamic property Longman\TelegramBot\Entities\Message::$text is deprecated in /var/www/app/plugins/Telegram/vendor/longman/telegram-bot/src/Entities/Entity.php on line 83

Deprecated: Creation of dynamic property Longman\TelegramBot\Entities\Message::$entities is deprecated in /var/www/app/plugins/Telegram/vendor/longman/telegram-bot/src/Entities/Entity.php on line 83

Deprecated: Creation of dynamic property Longman\TelegramBot\Entities\Message::$bot_username is deprecated in /var/www/app/plugins/Telegram/vendor/longman/telegram-bot/src/Entities/Entity.php on line 83

Deprecated: Creation of dynamic property Longman\TelegramBot\Entities\ServerResponse::$ok is deprecated in /var/www/app/plugins/Telegram/vendor/longman/telegram-bot/src/Entities/Entity.php on line 83

Deprecated: Creation of dynamic property Longman\TelegramBot\Entities\ServerResponse::$result is deprecated in /var/www/app/plugins/Telegram/vendor/longman/telegram-bot/src/Entities/Entity.php on line 83

Deprecated: Creation of dynamic property Longman\TelegramBot\Entities\ServerResponse::$raw_data is deprecated in /var/www/app/plugins/Telegram/vendor/longman/telegram-bot/src/Entities/Entity.php on line 83

Deprecated: Creation of dynamic property Longman\TelegramBot\Entities\ServerResponse::$bot_username is deprecated in /var/www/app/plugins/Telegram/vendor/longman/telegram-bot/src/Entities/Entity.php on line 83

Warning: Cannot modify header information - headers already sent by (output started at /var/www/app/plugins/Telegram/vendor/longman/telegram-bot/src/Entities/Entity.php:83) in /var/www/app/app/Core/Http/Response.php on line 222

Warning: Cannot modify header information - headers already sent by (output started at /var/www/app/plugins/Telegram/vendor/longman/telegram-bot/src/Entities/Entity.php:83) in /var/www/app/app/Core/Http/Response.php on line 222

Warning: Cannot modify header information - headers already sent by (output started at /var/www/app/plugins/Telegram/vendor/longman/telegram-bot/src/Entities/Entity.php:83) in /var/www/app/app/Core/Http/Response.php on line 222

Warning: Cannot modify header information - headers already sent by (output started at /var/www/app/plugins/Telegram/vendor/longman/telegram-bot/src/Entities/Entity.php:83) in /var/www/app/app/Core/Http/Response.php on line 222

Warning: Cannot modify header information - headers already sent by (output started at /var/www/app/plugins/Telegram/vendor/longman/telegram-bot/src/Entities/Entity.php:83) in /var/www/app/app/Core/Http/Response.php on line 222

Warning: Cannot modify header information - headers already sent by (output started at /var/www/app/plugins/Telegram/vendor/longman/telegram-bot/src/Entities/Entity.php:83) in /var/www/app/app/Core/Http/Response.php on line 222

Warning: Cannot modify header information - headers already sent by (output started at /var/www/app/plugins/Telegram/vendor/longman/telegram-bot/src/Entities/Entity.php:83) in /var/www/app/app/Core/Http/Response.php on line 222

</details>

What could be the issue? Thanks!

**Comment by manuvarkey** [comment]
Are notifications being received in Telegram ?  What is your PHP version ?

**Comment by Kor-Phaeron** [comment]
> Are notifications being received in Telegram ?

Yes, notifications are OK



> What is your PHP version ?

8.2.10

**Comment by Kor-Phaeron** [comment]
Maybe something wrong here?

 ![2023-12-05 115728](https://github.com/manuvarkey/kanboard-plugin-telegram/assets/60106051/29954db3-023a-4f96-b698-033d42557c66)

**Comment by manuvarkey** [comment]
I think the `longman/telegram-bot` package needs to be updated. Old version in used along with the current version.

I have updated the package to the latest version in the [dev](https://github.com/manuvarkey/kanboard-plugin-telegram/tree/dev) branch. Can you check if the warnings are reported with this ?

**Comment by Kor-Phaeron** [comment]
Hell yeah! It is seems like now is ok! Thanks a lot!
