### ISSUE TITLE
Request for new release: Update to latest master code

### ISSUE THREAD

**Issue by e-labInnovations** [manuvarkey/kanboard-plugin-telegram#48]
Hi @manuvarkey,
I'm requesting a new release of the plugin, based on the current master code.

As you may recall, I submitted a PR 4 months ago, which was merged into the master branch. However, there hasn't been a new release of the plugin since then, and the changes are still not reflected on the Kanboard plugin list.

I request that you consider releasing a new version of the plugin, incorporating the latest changes from the master branch. This would ensure that users can benefit from the updates and fixes that have been made.

If anything is holding up the release process, I'd be happy to help in any way I can. Please let me know if there's anything I can do to assist.

Thanks in advance for considering this request!

Best regards

**Comment by manuvarkey** [comment]
I have created a new release https://github.com/manuvarkey/kanboard-plugin-telegram/releases/tag/v1.6.0. Plugin will be available for update after merging of https://github.com/kanboard/website/pull/515.

**Comment by manuvarkey** [comment]
@e-labInnovations Missing translation template strings are to be added to various files under https://github.com/manuvarkey/kanboard-plugin-telegram/tree/master/Locale since changes where made during #45. If you have time give it a try!

**Comment by manuvarkey** [comment]
If you are interested join as a collaborator in this project. I have sent the invite.
