### ISSUE TITLE
Failed to receive message from tg bot

### ISSUE THREAD

**Issue by calilex** [manuvarkey/kanboard-plugin-telegram#49]
Version Info:
- kanboard v1.2.37
- kanboard-plugin-telegram  1.6.0

I can run the following commands successfully, which means I can send and receive message from my bot.
```bash
curl -X POST  -H "Content-Type: application/json" https://api.telegram.org/bot<Key>/sendMessage -d '{"chat_id": "xxxx", "text": "this is a test message"}'
curl https://api.telegram.org/bot<Key>/getUpdates
```
I can successfully `Get Chat ID` in `Integrations > Telegram`, but I cannot receive notification message whenever I create or delete a task in kanboard.

I don't know anything about PHP, but after some exploration, I found that sendMessage seems not to be triggered, or at least no request is sent to api.telegram.org.

**Comment by manuvarkey** [comment]
@calilex Please check this ....

https://github.com/manuvarkey/kanboard-plugin-telegram/issues/13#issuecomment-455528300

https://github.com/manuvarkey/kanboard-plugin-telegram/issues/33#issuecomment-1014449836

**Comment by calilex** [comment]
@manuvarkey Thank you for your explanation. This behavior is indeed a bit confusing.
